# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.33"
  config.vm.hostname = "<%= ProjectFolder %>.dev"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision "file", source: "ops/vagrant-nginx.conf", destination: "/tmp/vagrant-nginx.conf"
  config.vm.provision "file", source: "ops/99-vagrant-php.ini", destination: "/tmp/99-vagrant-php.ini"

  if Vagrant.has_plugin?('vagrant-bindfs')
    config.vm.synced_folder "./", "/mnt/vagrant-base",
      id: "repo",
      type: 'nfs',
      perms: "u=rwX:g=rwX:o=rD"
    config.bindfs.bind_folder "/mnt/vagrant-base", "/var/www/<%= ProjectFolder %>", 
      owner: 'www-data', 
      group: 'vagrant', 
      perms: "u=rwX:g=rwX:o=rD"
    config.vm.provision :shell,
      :path => "ops/vagrant-provisioning.sh", 
      :args => "/mnt/vagrant-base"
  else
    config.vm.synced_folder "./", "/var/www/<%= ProjectFolder %>", 
      owner: "www-data", 
      group: "vagrant",
      perms: "u=rwX:g=rwX:o=rD"

    config.vm.provision :shell,
      :path => "ops/vagrant-provisioning.sh", 
      :args => "/var/www/<%= ProjectFolder %>"
  end

end
